export const Movies = [
    {
        name: 'Army Of The Dead',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '1a.jpeg',
        image: '1.jpg',
        category: 'Western',
        language: 'English',
        year: '2022',
        time: '3hr',
        video: '',
        rate: 3.4,
        reviews: 23
    },
    {
        name: 'The Conjuring',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '22.jpg',
        image: '2.jpg',
        category: 'Thriller',
        language: 'Chineese',
        year: '1999',
        time: '4hr',
        video: '',
        rate: 3.4,
        reviews: 23
    },
    {
        name: 'My Favorite Person',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '33.jpg',
        image: '3.jpg',
        category: 'Adventure',
        language: 'Korean',
        year: '2000',
        time: '11hr',
        video: '',
        rate: 2.5,
        reviews: 2
    },
    {
        name: 'Lets Be Crops',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '44.jpg',
        image: '4.jpg',
        category: 'Musical',
        language: 'English',
        year: '2022',
        time: '1hr',
        video: '',
        rate: 1.5,
        reviews: 6
    },
    {
        name: 'Below Her Mouth',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '55.jpg',
        image: '5.jpg',
        category: 'Romance',
        language: 'English',
        year: '1899',
        time: '1hr',
        video: '',
        rate: 3.4,
        reviews: 23
    },
    {
        name: 'L\'amour des hommes',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '66.jpg',
        image: '6.jpg',
        category: 'Drama',
        language: 'Arabic',
        year: '2017',
        time: '1hr42',
        video: '',
        rate: 4,
        reviews: 28
    },
    {
        name: 'The Prodigy',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '77.jpg',
        image: '7.jpg',
        category: 'Drama',
        language: 'English',
        year: '2014',
        time: '1hr42',
        video: '',
        rate: 3.7,
        reviews: 1884
    },
    {
        name: 'Invitation To Murder',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        titleImage: '88.jpg',
        image: '8.jpg',
        category: 'Thriller',
        language: 'English',
        year: '2023',
        time: '2hrs',
        video: '',
        rate: 3.7,
        reviews: 1884
    }
]